[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/_worker"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/_worker"
  status = 200